import { PrismaClient, Category } from "@prisma/client";

const prisma = new PrismaClient();

type Entry = { phrase: string; hint: string };

const words: Record<Category, Entry[]> = {
  
    SPORT: [
      { phrase: "Tenis", hint: "Rakieta" },
      { phrase: "Boks", hint: "Ring" },
      { phrase: "Pływanie", hint: "Kraul" },
      { phrase: "Bieganie", hint: "Tętno" },
      { phrase: "Kolarstwo", hint: "Łańcuch" },
      { phrase: "Narciarstwo", hint: "Grawitacja" },
      { phrase: "Snowboard", hint: "Puch" },
      { phrase: "Hokej", hint: "Tafle" },
      { phrase: "Golf", hint: "Trawnik" },
      { phrase: "Rugby", hint: "Szarża" },
      { phrase: "Badminton", hint: "Aerodynamika" },
      { phrase: "Szermierka", hint: "Pojedynek" },
      { phrase: "Zapasy", hint: "Plecy" },
      { phrase: "Judo", hint: "Mata" },
      { phrase: "Karate", hint: "Okrzyk" },
      { phrase: "Wspinaczka", hint: "Pion" },
      { phrase: "Surfing", hint: "Ocean" },
      { phrase: "Wioślarstwo", hint: "Tyłem" },
      { phrase: "Rajdy", hint: "Szuter" },
      { phrase: "Baseball", hint: "Baza" },
      { phrase: "Triathlon", hint: "Wytrzymałość" },
      { phrase: "Łyżwiarstwo", hint: "Płozy" },
      { phrase: "Skateboarding", hint: "Kółka" },
      { phrase: "Parkour", hint: "Efektywność" },
      { phrase: "Kręgle", hint: "Geometria" },
      { phrase: "Darts", hint: "Precyzja" },
      { phrase: "Bilard", hint: "Sukno" },
      { phrase: "Crossfit", hint: "Intensywność" },
      { phrase: "Jogging", hint: "Rekreacja" },
      { phrase: "Maraton", hint: "Posłaniec" },
      { phrase: "Szachy", hint: "Arbiter" },
      { phrase: "Padel", hint: "Klatka" },
      { phrase: "Squash", hint: "Ściana" },
      { phrase: "Żeglarstwo", hint: "Wiatr" },
      { phrase: "Kulturystyka", hint: "Hipertrofia" }
    ],
    ZWIERZETA: [
      { phrase: "Pies", hint: "Węch" },
      { phrase: "Kot", hint: "Niezależność" },
      { phrase: "Lew", hint: "Grzywa" },
      { phrase: "Tygrys", hint: "Dżungla" },
      { phrase: "Słoń", hint: "Pamięć" },
      { phrase: "Żyrafa", hint: "Akacja" },
      { phrase: "Wilk", hint: "Księżyc" },
      { phrase: "Lis", hint: "Podstęp" },
      { phrase: "Niedźwiedź", hint: "Gawra" },
      { phrase: "Królik", hint: "Nora" },
      { phrase: "Mysz", hint: "Spiżarnia" },
      { phrase: "Szczur", hint: "Przetrwanie" },
      { phrase: "Koń", hint: "Kopyta" },
      { phrase: "Krowa", hint: "Przeżuwacz" },
      { phrase: "Owca", hint: "Stado" },
      { phrase: "Koza", hint: "Skały" },
      { phrase: "Świnia", hint: "Błoto" },
      { phrase: "Kura", hint: "Potomek" },
      { phrase: "Kaczka", hint: "Pióra" },
      { phrase: "Gęś", hint: "Alarm" },
      { phrase: "Orzeł", hint: "Godło" },
      { phrase: "Sokół", hint: "Prędkość" },
      { phrase: "Papuga", hint: "Egzotyka" },
      { phrase: "Pingwin", hint: "Frak" },
      { phrase: "Foka", hint: "Demon" },
      { phrase: "Delfin", hint: "Komunikacja" },
      { phrase: "Rekin", hint: "Zęby" },
      { phrase: "Wieloryb", hint: "Plankton" },
      { phrase: "Żółw", hint: "Pancerz" },
      { phrase: "Krokodyl", hint: "Ukrycie" },
      { phrase: "Wąż", hint: "Język" },
      { phrase: "Jaszczurka", hint: "Ogon" },
      { phrase: "Żaba", hint: "Metamorfoza" },
      { phrase: "Nietoperz", hint: "Zmrok" },
      { phrase: "Pszczoła", hint: "Nektar" },
      { phrase: "Motyl", hint: "Gąsienica" },
      { phrase: "Mrówka", hint: "Hierarchia" },
      { phrase: "Pająk", hint: "Konstrukcja" },
      { phrase: "Jeż", hint: "Zagrożenie" },
      { phrase: "Chomik", hint: "Transport" },
      { phrase: "Kameleon", hint: "Adaptacja" },
      { phrase: "Bóbr", hint: "Inżynier" },
      { phrase: "Koala", hint: "Eukaliptus" },
      { phrase: "Ośmiornica", hint: "Serca" },
      { phrase: "Lemur", hint: "Madagaskar" }
    ],
    JEDZENIE: [
      { phrase: "Pizza", hint: "Eksport" },
      { phrase: "Burger", hint: "Klasyk" },
      { phrase: "Spaghetti", hint: "Nitki" },
      { phrase: "Sushi", hint: "Sztuka" },
      { phrase: "Pierogi", hint: "Zawiniątka" },
      { phrase: "Bigos", hint: "Kapusta" },
      { phrase: "Żurek", hint: "Chleb" },
      { phrase: "Rosół", hint: "Wywar" },
      { phrase: "Pomidorowa", hint: "Poniedziałek" },
      { phrase: "Naleśniki", hint: "Zawijanie" },
      { phrase: "Gofry", hint: "Kurort" },
      { phrase: "Lody", hint: "Upał" },
      { phrase: "Czekolada", hint: "Tabliczka" },
      { phrase: "Sernik", hint: "Twaróg" },
      { phrase: "Jabłko", hint: "Mitologia" },
      { phrase: "Banan", hint: "Potas" },
      { phrase: "Pomarańcza", hint: "Cytrus" },
      { phrase: "Arbuz", hint: "Wnętrze" },
      { phrase: "Kanapka", hint: "Warstwy" },
      { phrase: "Tost", hint: "Temperatura" },
      { phrase: "Jajecznica", hint: "Białko" },
      { phrase: "Omlet", hint: "Puszystość" },
      { phrase: "Stek", hint: "Stopień" },
      { phrase: "Frytki", hint: "Słupki" },
      { phrase: "Kebab", hint: "Rożen" },
      { phrase: "Taco", hint: "Przekąska" },
      { phrase: "Burrito", hint: "Farsz" },
      { phrase: "Ramen", hint: "Esencja" },
      { phrase: "Curry", hint: "Aromaty" },
      { phrase: "Risotto", hint: "Konsystencja" },
      { phrase: "Lasagne", hint: "Beszamel" },
      { phrase: "Pesto", hint: "Oliwa" },
      { phrase: "Chleb", hint: "Tradycja" },
      { phrase: "Masło", hint: "Śmietanka" },
      { phrase: "Ser", hint: "Dojrzewanie" },
      { phrase: "Jogurt", hint: "Bakterie" },
      { phrase: "Miód", hint: "Substancja" },
      { phrase: "Orzechy", hint: "Skorupa" },
      { phrase: "Hummus", hint: "Ciecierzyca" },
      { phrase: "Krewetki", hint: "Różowe" },
      { phrase: "Muffinka", hint: "Papilotki" },
      { phrase: "Oliwa", hint: "Złoto" },
      { phrase: "Guacamole", hint: "Awokado" },
      { phrase: "Zupa", hint: "Płyn" },
      { phrase: "Makaron", hint: "Mąka" }
    ],
    MIEJSCE: [
      { phrase: "Szkoła", hint: "Dzwonek" },
      { phrase: "Szpital", hint: "Oddział" },
      { phrase: "Lotnisko", hint: "Kontrola" },
      { phrase: "Dworzec", hint: "Węzeł" },
      { phrase: "Plaża", hint: "Przypływ" },
      { phrase: "Góry", hint: "Rzeźba" },
      { phrase: "Las", hint: "Tlen" },
      { phrase: "Park", hint: "Tkanka" },
      { phrase: "Kino", hint: "Ekran" },
      { phrase: "Teatr", hint: "Sztuka" },
      { phrase: "Biblioteka", hint: "Cisza" },
      { phrase: "Muzeum", hint: "Dziedzictwo" },
      { phrase: "Restauracja", hint: "Serwis" },
      { phrase: "Kawiarnia", hint: "Ziarna" },
      { phrase: "Sklep", hint: "Transakcja" },
      { phrase: "Supermarket", hint: "Alejki" },
      { phrase: "Stadion", hint: "Widowisko" },
      { phrase: "Basen", hint: "Chlor" },
      { phrase: "Siłownia", hint: "Opór" },
      { phrase: "Biuro", hint: "Operacje" },
      { phrase: "Fabryka", hint: "Masa" },
      { phrase: "Magazyn", hint: "Hala" },
      { phrase: "Wieś", hint: "Gęstość" },
      { phrase: "Miasto", hint: "Infrastruktura" },
      { phrase: "Most", hint: "Przeszkoda" },
      { phrase: "Tunel", hint: "Drążenie" },
      { phrase: "Autostrada", hint: "Wielopasmowa" },
      { phrase: "Hotel", hint: "Standard" },
      { phrase: "Hostel", hint: "Budżet" },
      { phrase: "Zamek", hint: "Siedziba" },
      { phrase: "Rynek", hint: "Plac" },
      { phrase: "Kościół", hint: "Kult" },
      { phrase: "Cmentarz", hint: "Pamięć" },
      { phrase: "Komisariat", hint: "Jednostka" },
      { phrase: "Strażnica", hint: "Baza" },
      { phrase: "Port", hint: "Nabrzeże" },
      { phrase: "Przystanek", hint: "Trasa" },
      { phrase: "Apteka", hint: "Zalecenia" },
      { phrase: "Laboratorium", hint: "Analiza" },
      { phrase: "Pustynia", hint: "Erozja" },
      { phrase: "Planetarium", hint: "Kopuła" },
      { phrase: "ZOO", hint: "Ochrona" },
      { phrase: "Apteczka", hint: "Ratunek" },
      { phrase: "Piwnica", hint: "Fundament" },
      { phrase: "Garaż", hint: "Pojazd" }
    ],
    ZAWOD: [
      { phrase: "Lekarz", hint: "Naprawa" },
      { phrase: "Pielęgniarka", hint: "Koordynacja" },
      { phrase: "Nauczyciel", hint: "Podstawa" },
      { phrase: "Programista", hint: "Procesor" },
      { phrase: "Tester", hint: "Niedoskonałość" },
      { phrase: "Architekt", hint: "Koncepcja" },
      { phrase: "Budowlaniec", hint: "Rzemiosło" },
      { phrase: "Stolarz", hint: "Mebel" },
      { phrase: "Hydraulik", hint: "Dystrybucja" },
      { phrase: "Elektryk", hint: "Elektrony" },
      { phrase: "Mechanik", hint: "Układ" },
      { phrase: "Kierowca", hint: "Ładunek" },
      { phrase: "Pilot", hint: "Nawigacja" },
      { phrase: "Stewardessa", hint: "Wysokość" },
      { phrase: "Kucharz", hint: "Temperatura" },
      { phrase: "Kelner", hint: "Ambasador" },
      { phrase: "Barista", hint: "Napar" },
      { phrase: "Piekarz", hint: "Noc" },
      { phrase: "Rzeźnik", hint: "Rozbiór" },
      { phrase: "Rolnik", hint: "Ziemia" },
      { phrase: "Weterynarz", hint: "Pacjent" },
      { phrase: "Farmaceuta", hint: "Interakcja" },
      { phrase: "Sędzia", hint: "Toga" },
      { phrase: "Policjant", hint: "Porządek" },
      { phrase: "Strażak", hint: "Katastrofa" },
      { phrase: "Ratownik", hint: "Funkcje" },
      { phrase: "Żołnierz", hint: "Mundur" },
      { phrase: "Dziennikarz", hint: "Opinia" },
      { phrase: "Fotograf", hint: "Matryca" },
      { phrase: "Aktor", hint: "Scenariusz" },
      { phrase: "Muzyk", hint: "Fala" },
      { phrase: "DJ", hint: "Ścieżka" },
      { phrase: "Grafik", hint: "Typografia" },
      { phrase: "Księgowy", hint: "Podatki" },
      { phrase: "Sprzedawca", hint: "Potrzeba" },
      { phrase: "Magik", hint: "Percepcja" },
      { phrase: "Psycholog", hint: "Procesy" },
      { phrase: "Dietetyk", hint: "Biochemia" },
      { phrase: "Astronom", hint: "Atmosfera" },
      { phrase: "Archeolog", hint: "Szczątki" },
      { phrase: "Tłumacz", hint: "Most" },
      { phrase: "Górnik", hint: "Zasoby" },
      { phrase: "Malarz", hint: "Faktura" },
      { phrase: "Prawnik", hint: "Spór" }
    ],
    WYDARZENIE: [
      { phrase: "Wesele", hint: "Związek" },
      { phrase: "Urodziny", hint: "Cykl" },
      { phrase: "Sylwester", hint: "Kalendarz" },
      { phrase: "Koncert", hint: "Fani" },
      { phrase: "Turniej", hint: "Eliminacje" },
      { phrase: "Parada", hint: "Przemarsz" },
      { phrase: "Festiwal", hint: "Święto" },
      { phrase: "Konferencja", hint: "Wymiana" },
      { phrase: "Warsztaty", hint: "Teoria" },
      { phrase: "Szkolenie", hint: "Trener" },
      { phrase: "Egzamin", hint: "Weryfikacja" },
      { phrase: "Studniówka", hint: "Zima" },
      { phrase: "Matura", hint: "Dojrzałość" },
      { phrase: "Rekrutacja", hint: "Selekcja" },
      { phrase: "Hackathon", hint: "Prototyp" },
      { phrase: "Wyprzedaż", hint: "Czyszczenie" },
      { phrase: "Aukcja", hint: "Determinacja" },
      { phrase: "Targi", hint: "Wystawa" },
      { phrase: "Debata", hint: "Dyskusja" },
      { phrase: "Wybory", hint: "Demokracja" },
      { phrase: "Protest", hint: "Sprzeciw" },
      { phrase: "Chrzest", hint: "Sakrament" },
      { phrase: "Komunia", hint: "Maj" },
      { phrase: "Rocznica", hint: "Wspomnienie" },
      { phrase: "Piknik", hint: "Natura" },
      { phrase: "Grill", hint: "Żar" },
      { phrase: "Zaćmienie", hint: "Księżyc" },
      { phrase: "Przeprowadzka", hint: "Logistyka" },
      { phrase: "Konwent", hint: "Popkultura" },
      { phrase: "Rewolucja", hint: "Przełom" },
      { phrase: "Premiera", hint: "Debiut" },
      { phrase: "Pielgrzymka", hint: "Intencja" },
      { phrase: "Spektakl", hint: "Kurtyna" },
      { phrase: "Defilada", hint: "Szyk" },
      { phrase: "Bankiet", hint: "Prestiż" }
    ]
  
};

async function main() {
  await prisma.wordBank.deleteMany();
  for (const [category, entries] of Object.entries(words) as [Category, Entry[]][]) {
    for (const entry of entries) {
      await prisma.wordBank.create({
        data: {
          category,
          phrase: entry.phrase,
          hint: entry.hint
        }
      });
    }
  }
}

main()
  .then(async () => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
